### ISSUE TITLE
Minor Problems in Week5

### ISSUE THREAD

**Issue by rippleYJH** [hupili/python-for-data-and-media-communication-gitbook#28]
1. It is better explain to students Jupyter notebook would not present results on the screen except using "print()" command or type the variable in the new line. May causing confusion if we dont mention it.

2.   my_urls = data.find_all('a',attrs={'class':'post__title-link js-read-more'})
I am wondering why the value here is 'post__title-link js-read-more'? I only inspect this: <a class="post__title-link" href="../blog/20170407-open-data-hk/" itemprop="url">
                「消失的檔案」：香港開放數據大檢討
              </a>
Why not is this one: class="post__title-link" 

3.  One thing I can not clearly understand is the format part:
 my_url['href'].split('/blog')[-1]
Can you try to explain a little bit how can this return the format we want?

4. 

> for i in range(1,8):  #format all pages urls
        if i == 1:
            page_url = url
        else:
            page_url = '{url_initial}page/{number}/'.format(url_initial = url,number=i)
            #print(page_url)
Here using the if logic, if page ==1, then the page_url is url. If else, still need to be further formatted. My question is why we can not apply the same function to other pages? Aren't they sharing the same format?

Thanks for your hard work! Yes, this week is more difficult than before, but I think it is clear to follow. : ）

**Comment by ChicoXYC** [comment]
@rippleYJH Thanks so much!  Always express what may puzzle you and give a clear explanation of the questions, that's what we need in conversation. @ConnorLi96 Are you having the same problem? @hupili Hope I explain those clearly.

1. I add this note about `print` issue in Jupyter Notebook chapter, I guess students are easy to overlook to click into it. Therefore I added in chapter 4 again.  Basically, We can directly use parameters to print sth. Like the following example, in Jupyter Notebook, data equal to print(data)
```python
data = request.get(url)
data
print(data)
```

2. It's a good question, this is why I leave this question as a quiz. If you tried using the following method

```python
my_urls = data.find_all('a',attrs={'class':'post__title-link'})
```

The result will return two identical urls. Because, aside of `{'class':'post__title-link'}`, it will also find `{'class':'post__title-link js-read-more'}`. I don't really know why is this happen, but I guess the reason is that the second one also contains the attribute  `post__title-link`. Therefore, we need to specify our code further, to locate the url more precisely.

3. It's hard to explain word by word about this question. But I can simply express what and why we need to do this. You will find in the page(2-7), the articles url is a little bit different. We can use `href` key to get the link like the following:

```text
"../../../blog/20150905-pluto-size-visualization/"
```
You will see that it's not like we want. Firstly, it should have a `http://initiumlab.com` ahead of it. Secondly, we should omit those `../../..`. So `split()` function will help us to get this. you can try to split the `my_url['href']` by `blog` or `/blog` see what will happen, after split, its a list of elements, we can use `list[index]` to get what we want, and finally, use `string.format` to get the url.

4. I‘m not sure what you are asking.  
>why we can not apply the same function to other pages?

We use those for loop to format urls of page2-7. If you mean to use those methods to format other case examples. Its a case by case situation. In most cases, we just need to change the page number to format other pages. But in some cases, there are some characters and strings we need to handle. But the logic here is clear, we use control flows + string.format to build the url we want.
