### ISSUE TITLE
Week 3 Feedback

### ISSUE THREAD

**Issue by kaiwenxu94** [hupili/python-for-data-and-media-communication-gitbook#38]
1. The outputs in Example4 should contain no parentheses and no quotation marks.
![image](https://user-images.githubusercontent.com/42831899/45600051-0d0a3b80-ba29-11e8-9d33-df1227c51418.png)
Below is the right version:
	>>> x=4
	>>> y=6
	>>> print('x!=y:',x!=y)
	x!=y: True

2. Remember to add parentheses, and list2[1:5]means slicing list2 from index1 value to index5 value but does not include index5 value. Also, list2[:2] means slcing list2 from index0 value to index2 value but does not include index2 value.  We had better explain the rule of slicing lists more clearly. It confused me when I saw the outputs in the first place.
![image](https://user-images.githubusercontent.com/42831899/45600069-3dea7080-ba29-11e8-98a1-c276db3473c3.png)

3. Delete the command of the third line in example8.
![image](https://user-images.githubusercontent.com/42831899/45600074-4f337d00-ba29-11e8-9c0f-662758f44a23.png)

4. In Example10, there is no key named 'Frank' or its corresponding value. 
![image](https://user-images.githubusercontent.com/42831899/45600078-5fe3f300-ba29-11e8-938e-7e75a0dfa331.png)
If we try to access the value of a key that does not exist in the list, an error will be reported as follows:
![image](https://user-images.githubusercontent.com/42831899/45600080-64a8a700-ba29-11e8-9130-ecf65ac8599b.png)

5. In Example22, the last line（i=i+1）should only have one indentation, otherwise the output will be 1 endlessly and never breaks:
![image](https://user-images.githubusercontent.com/42831899/45600083-6f633c00-ba29-11e8-942f-1e00149e85a4.png)
![image](https://user-images.githubusercontent.com/42831899/45600096-96217280-ba29-11e8-85db-18db7a347478.png)
Below is the right version:
![image](https://user-images.githubusercontent.com/42831899/45600099-a20d3480-ba29-11e8-9223-4b1de659b6de.png)

6. In the first line, the input('please input a int:') will produce a string, and the type of a string is never equal to the type of 1. Hence, ValueError will be always raised if you put either 2 or 2.2. The 2 and 2.2 you input are strings. Therefore, you need to add a int() function before the input(), because int('2.2') leads to a ValueError while int('2') can produce an int.
![image](https://user-images.githubusercontent.com/42831899/45600102-b5b89b00-ba29-11e8-85eb-04037a35820b.png)
Also, in the last line, remember to add parenthesis: print (inputValue)
The right version should be:
![image](https://user-images.githubusercontent.com/42831899/45600104-c1a45d00-ba29-11e8-8e16-f49f18be3b54.png)

**Comment by ChicoXYC** [comment]
@kaiwenxu94  thanks a lot. I will modify right now.

**Comment by ChicoXYC** [comment]
@kaiwenxu94 there are some issues 
Q4.
![person dict](https://user-images.githubusercontent.com/37010763/45605332-e7078a00-ba6e-11e8-94b5-3b4eff35c324.jpg)
you can add a new item by creating a new key with its value.  I guess you got `key error` is because you type the wrong dict name. the dict here is `person_dict`

Q6. I've been already deleted this example days before, because its wrong.

First of all, the logic here is kind of tricky. if you `int()` all numbers you input, the results should all be integers, therefore its meaningless to compare.
Secondly. After you input a number, it will convert to `string`, its by default, right? But `int()` function cannot convert a string with a float number, if you input a float number. Say if you input `2.2`. it should be a float, but under this command line `inputValue = int(input('please input a int:'))`, its still a string and get another error 'invalid literal for int() with base 10' which is not what we discuss.

**Comment by ChicoXYC** [comment]
@hupili OK, I will pay more attention.
