### ISSUE TITLE
A question about week-06

### ISSUE THREAD

**Issue by Catmint1215** [hupili/python-for-data-and-media-communication-gitbook#41]
# Week-06
![image](https://user-images.githubusercontent.com/42177490/45799200-423fb380-bcdf-11e8-93d3-4683d4fa2c3f.png)
In this part of week-06, it shows "by_link_text". But only when I change it to "by_partial_link_text", can it works.
![image](https://user-images.githubusercontent.com/42177490/45799347-c3974600-bcdf-11e8-9934-ec58c5fd05df.png)
I am confused about when should we use "partial".

**Comment by ChicoXYC** [comment]
@Catmint1215  Good question, I think this is because the link text is changing in Google search.  I will update in the notes.

Basically, you can tell the difference by their names.
`link_text`: it returns elements with an **exact** match of the given text.
 `partial_link_text`: returns elements which **include** the given text.

For the example we demo, except the text we search, there is some extra words `An ...`
![find-text-link-by-partiallinktext](https://user-images.githubusercontent.com/37010763/45809874-e6cfee80-bcfb-11e8-973e-cdbc19d7a6b7.jpg)
Thats the reason why you cannot find the elements in the precise match mode.

**Comment by Catmint1215** [comment]
> @Catmint1215 Good question, I think this is because the link text is changing in Google search. I will update in the notes.
> 
> Basically, you can tell the difference by their names.
> `link_text`: it returns elements with an **exact** match of the given text.
> `partial_link_text`: returns elements which **include** the given text.
> 
> For the example we demo, except the text we search, there is some extra words `An ...`
> ![find-text-link-by-partiallinktext](https://user-images.githubusercontent.com/37010763/45809874-e6cfee80-bcfb-11e8-973e-cdbc19d7a6b7.jpg)
> Thats the reason why you cannot find the elements in the precise match mode.



> @Catmint1215 Good question, I think this is because the link text is changing in Google search. I will update in the notes.
> 
> Basically, you can tell the difference by their names.
> `link_text`: it returns elements with an **exact** match of the given text.
> `partial_link_text`: returns elements which **include** the given text.
> 
> For the example we demo, except the text we search, there is some extra words `An ...`
> ![find-text-link-by-partiallinktext](https://user-images.githubusercontent.com/37010763/45809874-e6cfee80-bcfb-11e8-973e-cdbc19d7a6b7.jpg)
> Thats the reason why you cannot find the elements in the precise match mode.

Thanks a lot! 师兄~
