### ISSUE TITLE
How to scrape more than one page in a more efficient way

### ISSUE THREAD

**Issue by lullabymia** [hupili/python-for-data-and-media-communication-gitbook#64]
I tried to scrape 10 pages from douban and only find this stupid way(define a function called scraper and change the url every time). But is there a better solution?
 I googled it and found a way to import **scrapy** but found it too difficult to understand.
<img width="668" alt="2018-11-03 11 45 52" src="https://user-images.githubusercontent.com/42403858/47947816-fe3b0200-df5e-11e8-8df2-14f191153fc5.png">
<img width="648" alt="2018-11-03 11 46 10" src="https://user-images.githubusercontent.com/42403858/47947819-06933d00-df5f-11e8-9569-fca1d54ffb1c.png">
@ChicoXYC

**Comment by hupili** [comment]
@lullabymia There are several building blocks to optimise the codes:

- Use `for` and `range` to iterate over the `start` variable
- Use `str.format` to make the full request URL
- Use `list.extend` to concatenate the results in `for` loop

@FLYSTEPHEN  once demoed a similar case when crawling a job site. Can you also put the link here for other's reference?

**Comment by lullabymia** [comment]
<img width="754" alt="2018-11-05 11 25 21" src="https://user-images.githubusercontent.com/42403858/47976483-8ea74d00-e0ed-11e8-82e1-d4d0d44ed700.png">
I followed your instruction but encountered with another problem. When I print(data) outside the while loop, there is only the information about the last webpage. But it is whole data inside the loop. 
Then I try to write a csv file inside the loop. It turns out to be the last page as well. Anybody know what is wrong with it?
<img width="650" alt="2018-11-05 11 29 21" src="https://user-images.githubusercontent.com/42403858/47976677-7be14800-e0ee-11e8-98f2-0ae9c22b4bc4.png">
<img width="733" alt="2018-11-05 11 33 13" src="https://user-images.githubusercontent.com/42403858/47976692-a206e800-e0ee-11e8-9572-346e9dd73de4.png">

**Comment by hupili** [comment]
`list.extend` in the loop can solve this issue. Passing to @ChicoXYC

**Comment by ChicoXYC** [comment]
@lullabymia You've already found the problem, if you print in the `for loop` or `while condition`, it will only return the last. Two ways to solve the problem.

1. write csv in append mode.

```python
with open('doubanfix.csv', 'a') as f:
``` 
this will append every page's data into this csv.

2. list.extend

```python
data_total = []
i = 10
while i<0:
...
    data_total.extend(scraper(url))
... #others remain the same
```
Hope it will work for you, and please tell me whether it can be successful.

**Comment by FLYSTEPHEN** [comment]
- You've already solve the problem. You can still refer to the [job-radar](https://github.com/FLYSTEPHEN/DJ-job-radar/blob/master/job-radar.py) to make your codes more reusable. You can also give your advice to help us improve.
In this case we use 2 variables: 'page_index += step' to replace 'i = i+1', so that we can handle different websites with one series of codes. 
- BTW in @ChicoXYC 's comment, the point is to use ```open('doubanfix.csv', 'a')``` instead of ```open('doubanfix.csv', 'w')```. You can check their difference [here](https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/notes-week-04.md#file-operation) in our openbook. You will find that if we use 'w', the csv file will be rewritten from an empty file in every turn of a loop so that we can only get the last page's data.

**Comment by lullabymia** [comment]
It worked like magic! Thank you! @ChicoXYC
