### ISSUE TITLE
I cannot find required number in the tag.

### ISSUE THREAD

**Issue by Rita0719** [hupili/python-for-data-and-media-communication-gitbook#67]
* Operating system:Mac os
* Python version:py3
* Hardware:mac pro 
* Internet access:wifi
* Jupyter notebook or not? [Y/N]:y
* Which chapter of book?:5

I cannot find required number in the tag.
My dataset is about to scrape the top20 popular original works in main media genres on the AO3(https://archiveofourown.org/media).
The number of fan work cannot to be scraped since it is not in the tag.
<img width="1081" alt="2018-11-06 12 15 18" src="https://user-images.githubusercontent.com/42727192/48042680-b8c84000-e1bd-11e8-905d-357ab67476ad.png">

data fields are as bellows

genre - String. e.g.Anime & Manga

fanwork number - Int.e.g.36

original works name - String.e.g Haikyuu!!

my code is as bellows:

import requests 
from bs4 import BeautifulSoup
r = requests.get('https://archiveofourown.org/media')
html_str = r.text #get the content of the request
data = BeautifulSoup(html_str,"html.parser")
my_h1 = data.find('h1') # 查找网页主页标题
my_title = my_h1.text 
print(my_title.strip())
my_h2 = data.find('h2') # 查找网页主页副标题
my_title2 = my_h2.text 
print(my_title2.strip())

my_bookname=data.find_all('a')#查找各书名
for tag in my_bookname:
    print (tag.text)

headers = ['bookname','num']
from csv import*
import csv
with open('list.csv','w',newline='')as f:
 f_csv=csv.writer(f)
 if(headers):
    f_csv.writerow(headers)
    if(tag.text):
        f_csv.writerows(tag.text)

## Describe the efforts you have spent on this issue
This is the structure of Douban and the number of viewers is in the tag.
![wechatimg1866](https://user-images.githubusercontent.com/42727192/48042753-12c90580-e1be-11e8-884b-c42d3322797b.png)
I don't know if it is the problem of ao3 or I just get it wrong.hope you can help me.Thank you!

**Comment by ChicoXYC** [comment]
@Rita0719  You can find the number is in the `li` tag. Therefore you can use `li.text` to get the number. Since the book title also in the `li` tag. You can use `split()` function to separate those two elements and use `list slicing` to get the number.

Apart from the finding numbers. Its strongly suggested the `elements first` method to loacate the data you are interested in. 

Like, you should find the session first. 
![image](https://user-images.githubusercontent.com/37010763/48045747-8d991d00-e1cc-11e8-81c4-befce4a0c439.png)

And in each session, you can use `for loop` to get 4-5 books. And find title, review number in each book. This way is more logical clearly instead of directly find the all books title. You can refer to the following codes.

```python
book_session = data.find_all('li', attrs={'class':"medium listbox group"})
books=[]
for session in book_session:
    elements = session.find_all('li')    
    for element in elements:
        book = {}
        book['name'] = element.find('a').text
        book['reviews'] = element.text.strip().split('\n')[-1].strip()
        books.append(book)
```

**Comment by Rita0719** [comment]
thank you!code runs smoothly but there is another small problem. some book name is Japanese so when I look up to the csv file it will become an error code. it is because that the encode form different from Chinese?

**Comment by hupili** [comment]
@Rita0719 does this solve your issue? 

https://github.com/hupili/python-for-data-and-media-communication-gitbook/blob/master/module-csv.md#encoding-issue-about-microsoft-excel

**Comment by Rita0719** [comment]
thank you！
