### ISSUE TITLE
Problems about wordcloud

### ISSUE THREAD

**Issue by Shinonomee** [hupili/python-for-data-and-media-communication-gitbook#95]
Here is my code:
```
from wordcloud import WordCloud
import matplotlib.pyplot as plt
text = open('keywords.csv','r').read()
wordcloud = WordCloud().generate(text)
plt.imshow(wordcloud)
plt.axis('off')
plt.show()

wordcloud.to_file('Osaka.jpg')
```
The value Error is : We need at least 1 word to plot a word cloud, got 0.
Thank you very much!

**Comment by ChicoXYC** [comment]
@Shinonomee please first check out what is `text`, then we can discuss further.
Also, please upload your notebook and data in your one repo, and send us the link so that we can know what's the situation here.

**Comment by Shinonomee** [comment]
@ChicoXYC  [https://github.com/Shinonomee/Booking](url)
Here is the data and notebook, Thank you!

**Comment by ChicoXYC** [comment]
@Shinonomee 
<img width="769" alt="screen shot 2018-11-22 at 11 49 43 am" src="https://user-images.githubusercontent.com/37010763/48880832-1f4f8e00-ee4d-11e8-9c3c-3b11e3e84aab.png">
first, you csv has some error when written, please check out the scraping process. 

second, the value error indicates that you need to check out the `text` whether there is `text` or not. according to my test, the issue here is  `UnicodeDecodeError: 'utf-8' codec can't decode...`

change the encoding method will work.

```python
from wordcloud import WordCloud
import matplotlib.pyplot as plt
text = open('keywords.csv','r',encoding = "ISO-8859-1").read()
wordcloud = WordCloud().generate(text)
plt.imshow(wordcloud)
plt.axis('off')
plt.show()
```

**Comment by Shinonomee** [comment]
Thank you! The problem has been solved!
